FROM golang:1.25.9-trixie AS proto-builder

RUN apt-get update && apt-get install -y protobuf-compiler

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /proto-gen

COPY proto/ ./proto/

RUN protoc \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        proto/ranktrack.proto

FROM golang:1.26.2-trixie AS go-builder

workdir /app

COPY go.mod go.sum .

RUN go mod download

COPY internal/ ./internal/

COPY cmd/main.go ./cmd/main.go

COPY --from=proto-builder /proto-gen/proto/*.pb.go ./proto/

RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server-exe ./cmd/main.go

FROM debian:bookworm-slim

WORKDIR /root/

COPY --from=go-builder /app/server-exe .

EXPOSE 50051

CMD ["./server-exe"]


