// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/ranktrack.proto

package ranktrackv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankTrackService_ListRankings_FullMethodName   = "/ranktrack.v1.RankTrackService/ListRankings"
	RankTrackService_GetPlayer_FullMethodName      = "/ranktrack.v1.RankTrackService/GetPlayer"
	RankTrackService_ListTrajectory_FullMethodName = "/ranktrack.v1.RankTrackService/ListTrajectory"
)

// RankTrackServiceClient is the client API for RankTrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankTrackServiceClient interface {
	ListRankings(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*ListRankingsResponse, error)
	GetPlayer(ctx context.Context, in *GetPlayerRequest, opts ...grpc.CallOption) (*GetPlayerResponse, error)
	ListTrajectory(ctx context.Context, in *GetTrajectoryRequest, opts ...grpc.CallOption) (*ListTrajectoryResponse, error)
}

type rankTrackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankTrackServiceClient(cc grpc.ClientConnInterface) RankTrackServiceClient {
	return &rankTrackServiceClient{cc}
}

func (c *rankTrackServiceClient) ListRankings(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*ListRankingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRankingsResponse)
	err := c.cc.Invoke(ctx, RankTrackService_ListRankings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankTrackServiceClient) GetPlayer(ctx context.Context, in *GetPlayerRequest, opts ...grpc.CallOption) (*GetPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerResponse)
	err := c.cc.Invoke(ctx, RankTrackService_GetPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankTrackServiceClient) ListTrajectory(ctx context.Context, in *GetTrajectoryRequest, opts ...grpc.CallOption) (*ListTrajectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrajectoryResponse)
	err := c.cc.Invoke(ctx, RankTrackService_ListTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankTrackServiceServer is the server API for RankTrackService service.
// All implementations must embed UnimplementedRankTrackServiceServer
// for forward compatibility.
type RankTrackServiceServer interface {
	ListRankings(context.Context, *GetRankingRequest) (*ListRankingsResponse, error)
	GetPlayer(context.Context, *GetPlayerRequest) (*GetPlayerResponse, error)
	ListTrajectory(context.Context, *GetTrajectoryRequest) (*ListTrajectoryResponse, error)
	mustEmbedUnimplementedRankTrackServiceServer()
}

// UnimplementedRankTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankTrackServiceServer struct{}

func (UnimplementedRankTrackServiceServer) ListRankings(context.Context, *GetRankingRequest) (*ListRankingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRankings not implemented")
}
func (UnimplementedRankTrackServiceServer) GetPlayer(context.Context, *GetPlayerRequest) (*GetPlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayer not implemented")
}
func (UnimplementedRankTrackServiceServer) ListTrajectory(context.Context, *GetTrajectoryRequest) (*ListTrajectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrajectory not implemented")
}
func (UnimplementedRankTrackServiceServer) mustEmbedUnimplementedRankTrackServiceServer() {}
func (UnimplementedRankTrackServiceServer) testEmbeddedByValue()                          {}

// UnsafeRankTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankTrackServiceServer will
// result in compilation errors.
type UnsafeRankTrackServiceServer interface {
	mustEmbedUnimplementedRankTrackServiceServer()
}

func RegisterRankTrackServiceServer(s grpc.ServiceRegistrar, srv RankTrackServiceServer) {
	// If the following call panics, it indicates UnimplementedRankTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankTrackService_ServiceDesc, srv)
}

func _RankTrackService_ListRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankTrackServiceServer).ListRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankTrackService_ListRankings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankTrackServiceServer).ListRankings(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankTrackService_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankTrackServiceServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankTrackService_GetPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankTrackServiceServer).GetPlayer(ctx, req.(*GetPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankTrackService_ListTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankTrackServiceServer).ListTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankTrackService_ListTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankTrackServiceServer).ListTrajectory(ctx, req.(*GetTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankTrackService_ServiceDesc is the grpc.ServiceDesc for RankTrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankTrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranktrack.v1.RankTrackService",
	HandlerType: (*RankTrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRankings",
			Handler:    _RankTrackService_ListRankings_Handler,
		},
		{
			MethodName: "GetPlayer",
			Handler:    _RankTrackService_GetPlayer_Handler,
		},
		{
			MethodName: "ListTrajectory",
			Handler:    _RankTrackService_ListTrajectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ranktrack.proto",
}
