// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ranktrack.proto

package ranktrackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Get Ranking
type GetRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  string                 `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Country       *string                `protobuf:"bytes,3,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Date          *string                `protobuf:"bytes,4,opt,name=date,proto3,oneof" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingRequest) Reset() {
	*x = GetRankingRequest{}
	mi := &file_proto_ranktrack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingRequest) ProtoMessage() {}

func (x *GetRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingRequest.ProtoReflect.Descriptor instead.
func (*GetRankingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{0}
}

func (x *GetRankingRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *GetRankingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRankingRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *GetRankingRequest) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

// Response the ranking
type RankingEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Position         int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	PreviousPosition int32                  `protobuf:"varint,2,opt,name=previous_position,json=previousPosition,proto3" json:"previous_position,omitempty"`
	Momentum         float32                `protobuf:"fixed32,3,opt,name=momentum,proto3" json:"momentum,omitempty"`
	Volatility       float32                `protobuf:"fixed32,4,opt,name=volatility,proto3" json:"volatility,omitempty"`
	Points           int32                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	PreviousPoints   int32                  `protobuf:"varint,6,opt,name=previous_points,json=previousPoints,proto3" json:"previous_points,omitempty"`
	BestPosition     int32                  `protobuf:"varint,7,opt,name=best_position,json=bestPosition,proto3" json:"best_position,omitempty"`
	Player           *PlayerInfo            `protobuf:"bytes,8,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RankingEntry) Reset() {
	*x = RankingEntry{}
	mi := &file_proto_ranktrack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingEntry) ProtoMessage() {}

func (x *RankingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingEntry.ProtoReflect.Descriptor instead.
func (*RankingEntry) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{1}
}

func (x *RankingEntry) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RankingEntry) GetPreviousPosition() int32 {
	if x != nil {
		return x.PreviousPosition
	}
	return 0
}

func (x *RankingEntry) GetMomentum() float32 {
	if x != nil {
		return x.Momentum
	}
	return 0
}

func (x *RankingEntry) GetVolatility() float32 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *RankingEntry) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *RankingEntry) GetPreviousPoints() int32 {
	if x != nil {
		return x.PreviousPoints
	}
	return 0
}

func (x *RankingEntry) GetBestPosition() int32 {
	if x != nil {
		return x.BestPosition
	}
	return 0
}

func (x *RankingEntry) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

// Response Ranking Info
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_proto_ranktrack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PlayerInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type ListRankingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rankings      []*RankingEntry        `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRankingsResponse) Reset() {
	*x = ListRankingsResponse{}
	mi := &file_proto_ranktrack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRankingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRankingsResponse) ProtoMessage() {}

func (x *ListRankingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRankingsResponse.ProtoReflect.Descriptor instead.
func (*ListRankingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{3}
}

func (x *ListRankingsResponse) GetRankings() []*RankingEntry {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *ListRankingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Request datails player
type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_proto_ranktrack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// Response Player details
type GetPlayerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Player          *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	CurrentPosition int32                  `protobuf:"varint,2,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	CurrentPoints   int32                  `protobuf:"varint,3,opt,name=current_points,json=currentPoints,proto3" json:"current_points,omitempty"`
	BestPosition    int32                  `protobuf:"varint,4,opt,name=best_position,json=bestPosition,proto3" json:"best_position,omitempty"`
	Momentum        float32                `protobuf:"fixed32,5,opt,name=momentum,proto3" json:"momentum,omitempty"`
	Volatility      float32                `protobuf:"fixed32,6,opt,name=volatility,proto3" json:"volatility,omitempty"`
	Organization    string                 `protobuf:"bytes,7,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_proto_ranktrack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayerResponse) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GetPlayerResponse) GetCurrentPosition() int32 {
	if x != nil {
		return x.CurrentPosition
	}
	return 0
}

func (x *GetPlayerResponse) GetCurrentPoints() int32 {
	if x != nil {
		return x.CurrentPoints
	}
	return 0
}

func (x *GetPlayerResponse) GetBestPosition() int32 {
	if x != nil {
		return x.BestPosition
	}
	return 0
}

func (x *GetPlayerResponse) GetMomentum() float32 {
	if x != nil {
		return x.Momentum
	}
	return 0
}

func (x *GetPlayerResponse) GetVolatility() float32 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *GetPlayerResponse) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

// Reqpuest Trajectory
type GetTrajectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	PlayerRivalId *int32                 `protobuf:"varint,3,opt,name=player_rival_id,json=playerRivalId,proto3,oneof" json:"player_rival_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrajectoryRequest) Reset() {
	*x = GetTrajectoryRequest{}
	mi := &file_proto_ranktrack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrajectoryRequest) ProtoMessage() {}

func (x *GetTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*GetTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{6}
}

func (x *GetTrajectoryRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GetTrajectoryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetTrajectoryRequest) GetPlayerRivalId() int32 {
	if x != nil && x.PlayerRivalId != nil {
		return *x.PlayerRivalId
	}
	return 0
}

type TrajectoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Points        int32                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrajectoryPoint) Reset() {
	*x = TrajectoryPoint{}
	mi := &file_proto_ranktrack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrajectoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryPoint) ProtoMessage() {}

func (x *TrajectoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryPoint.ProtoReflect.Descriptor instead.
func (*TrajectoryPoint) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{7}
}

func (x *TrajectoryPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TrajectoryPoint) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *TrajectoryPoint) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type ListTrajectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1       []*TrajectoryPoint     `protobuf:"bytes,1,rep,name=player1,proto3" json:"player1,omitempty"`
	Player2       []*TrajectoryPoint     `protobuf:"bytes,2,rep,name=player2,proto3" json:"player2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrajectoryResponse) Reset() {
	*x = ListTrajectoryResponse{}
	mi := &file_proto_ranktrack_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrajectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrajectoryResponse) ProtoMessage() {}

func (x *ListTrajectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranktrack_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrajectoryResponse.ProtoReflect.Descriptor instead.
func (*ListTrajectoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_ranktrack_proto_rawDescGZIP(), []int{8}
}

func (x *ListTrajectoryResponse) GetPlayer1() []*TrajectoryPoint {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *ListTrajectoryResponse) GetPlayer2() []*TrajectoryPoint {
	if x != nil {
		return x.Player2
	}
	return nil
}

var File_proto_ranktrack_proto protoreflect.FileDescriptor

const file_proto_ranktrack_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ranktrack.proto\x12\franktrack.v1\"\x9a\x01\n" +
	"\x11GetRankingRequest\x12\"\n" +
	"\forganization\x18\x01 \x01(\tR\forganization\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\acountry\x18\x03 \x01(\tH\x00R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04date\x18\x04 \x01(\tH\x01R\x04date\x88\x01\x01B\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_date\"\xab\x02\n" +
	"\fRankingEntry\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12+\n" +
	"\x11previous_position\x18\x02 \x01(\x05R\x10previousPosition\x12\x1a\n" +
	"\bmomentum\x18\x03 \x01(\x02R\bmomentum\x12\x1e\n" +
	"\n" +
	"volatility\x18\x04 \x01(\x02R\n" +
	"volatility\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x05R\x06points\x12'\n" +
	"\x0fprevious_points\x18\x06 \x01(\x05R\x0epreviousPoints\x12#\n" +
	"\rbest_position\x18\a \x01(\x05R\fbestPosition\x120\n" +
	"\x06player\x18\b \x01(\v2\x18.ranktrack.v1.PlayerInfoR\x06player\"e\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"d\n" +
	"\x14ListRankingsResponse\x126\n" +
	"\brankings\x18\x01 \x03(\v2\x1a.ranktrack.v1.RankingEntryR\brankings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x10GetPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\"\x9c\x02\n" +
	"\x11GetPlayerResponse\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.ranktrack.v1.PlayerInfoR\x06player\x12)\n" +
	"\x10current_position\x18\x02 \x01(\x05R\x0fcurrentPosition\x12%\n" +
	"\x0ecurrent_points\x18\x03 \x01(\x05R\rcurrentPoints\x12#\n" +
	"\rbest_position\x18\x04 \x01(\x05R\fbestPosition\x12\x1a\n" +
	"\bmomentum\x18\x05 \x01(\x02R\bmomentum\x12\x1e\n" +
	"\n" +
	"volatility\x18\x06 \x01(\x02R\n" +
	"volatility\x12\"\n" +
	"\forganization\x18\a \x01(\tR\forganization\"\x8c\x01\n" +
	"\x14GetTrajectoryRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12+\n" +
	"\x0fplayer_rival_id\x18\x03 \x01(\x05H\x00R\rplayerRivalId\x88\x01\x01B\x12\n" +
	"\x10_player_rival_id\"Y\n" +
	"\x0fTrajectoryPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x05R\x06points\"\x8a\x01\n" +
	"\x16ListTrajectoryResponse\x127\n" +
	"\aplayer1\x18\x01 \x03(\v2\x1d.ranktrack.v1.TrajectoryPointR\aplayer1\x127\n" +
	"\aplayer2\x18\x02 \x03(\v2\x1d.ranktrack.v1.TrajectoryPointR\aplayer22\x91\x02\n" +
	"\x10RankTrackService\x12S\n" +
	"\fListRankings\x12\x1f.ranktrack.v1.GetRankingRequest\x1a\".ranktrack.v1.ListRankingsResponse\x12L\n" +
	"\tGetPlayer\x12\x1e.ranktrack.v1.GetPlayerRequest\x1a\x1f.ranktrack.v1.GetPlayerResponse\x12Z\n" +
	"\x0eListTrajectory\x12\".ranktrack.v1.GetTrajectoryRequest\x1a$.ranktrack.v1.ListTrajectoryResponseB9Z7github.com/tip-platform/tip-ranktrack/proto;ranktrackv1b\x06proto3"

var (
	file_proto_ranktrack_proto_rawDescOnce sync.Once
	file_proto_ranktrack_proto_rawDescData []byte
)

func file_proto_ranktrack_proto_rawDescGZIP() []byte {
	file_proto_ranktrack_proto_rawDescOnce.Do(func() {
		file_proto_ranktrack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ranktrack_proto_rawDesc), len(file_proto_ranktrack_proto_rawDesc)))
	})
	return file_proto_ranktrack_proto_rawDescData
}

var file_proto_ranktrack_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ranktrack_proto_goTypes = []any{
	(*GetRankingRequest)(nil),      // 0: ranktrack.v1.GetRankingRequest
	(*RankingEntry)(nil),           // 1: ranktrack.v1.RankingEntry
	(*PlayerInfo)(nil),             // 2: ranktrack.v1.PlayerInfo
	(*ListRankingsResponse)(nil),   // 3: ranktrack.v1.ListRankingsResponse
	(*GetPlayerRequest)(nil),       // 4: ranktrack.v1.GetPlayerRequest
	(*GetPlayerResponse)(nil),      // 5: ranktrack.v1.GetPlayerResponse
	(*GetTrajectoryRequest)(nil),   // 6: ranktrack.v1.GetTrajectoryRequest
	(*TrajectoryPoint)(nil),        // 7: ranktrack.v1.TrajectoryPoint
	(*ListTrajectoryResponse)(nil), // 8: ranktrack.v1.ListTrajectoryResponse
}
var file_proto_ranktrack_proto_depIdxs = []int32{
	2, // 0: ranktrack.v1.RankingEntry.player:type_name -> ranktrack.v1.PlayerInfo
	1, // 1: ranktrack.v1.ListRankingsResponse.rankings:type_name -> ranktrack.v1.RankingEntry
	2, // 2: ranktrack.v1.GetPlayerResponse.player:type_name -> ranktrack.v1.PlayerInfo
	7, // 3: ranktrack.v1.ListTrajectoryResponse.player1:type_name -> ranktrack.v1.TrajectoryPoint
	7, // 4: ranktrack.v1.ListTrajectoryResponse.player2:type_name -> ranktrack.v1.TrajectoryPoint
	0, // 5: ranktrack.v1.RankTrackService.ListRankings:input_type -> ranktrack.v1.GetRankingRequest
	4, // 6: ranktrack.v1.RankTrackService.GetPlayer:input_type -> ranktrack.v1.GetPlayerRequest
	6, // 7: ranktrack.v1.RankTrackService.ListTrajectory:input_type -> ranktrack.v1.GetTrajectoryRequest
	3, // 8: ranktrack.v1.RankTrackService.ListRankings:output_type -> ranktrack.v1.ListRankingsResponse
	5, // 9: ranktrack.v1.RankTrackService.GetPlayer:output_type -> ranktrack.v1.GetPlayerResponse
	8, // 10: ranktrack.v1.RankTrackService.ListTrajectory:output_type -> ranktrack.v1.ListTrajectoryResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_ranktrack_proto_init() }
func file_proto_ranktrack_proto_init() {
	if File_proto_ranktrack_proto != nil {
		return
	}
	file_proto_ranktrack_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_ranktrack_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ranktrack_proto_rawDesc), len(file_proto_ranktrack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ranktrack_proto_goTypes,
		DependencyIndexes: file_proto_ranktrack_proto_depIdxs,
		MessageInfos:      file_proto_ranktrack_proto_msgTypes,
	}.Build()
	File_proto_ranktrack_proto = out.File
	file_proto_ranktrack_proto_goTypes = nil
	file_proto_ranktrack_proto_depIdxs = nil
}
